#!/bin/bash

# Directory where to store temporary data
TMP_DIR="$HOME/.config/rmpc/tmp/"

# Ensure the directory is created
mkdir -p "$TMP_DIR"

# Where to temporarily store the album art received from rmpc
ALBUM_ART_PATH="$TMP_DIR/notification_cover"

# Path to fallback album art if no album art is found by rmpc/mpd
# Change this to your needs
DEFAULT_ALBUM_ART_PATH="$TMP_DIR/default_album_art.jpg"

# Save album art of the currently playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
	# Use default album art if rmpc returns non-zero exit code
	ALBUM_ART_PATH="${DEFAULT_ALBUM_ART_PATH}"
fi

# Send the notification
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	notify-send -i "${ALBUM_ART_PATH}" "Now Playing" "$ARTIST - $TITLE"
elif [[ "$OSTYPE" == "darwin"* ]]; then
	# appIcon doesn't work as of Sonoma 15.4.1 (time of writing)
	# /opt/homebrew/bin/terminal-notifier -appIcon "${ALBUM_ART_PATH}" -title "Now Playing" -message "$ARTIST - $TITLE"
	/opt/homebrew/bin/terminal-notifier -title "Now Playing" -message "$ARTIST - $TITLE"
fi
