#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	c="clear" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -ravp" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -a" \
	exa="exa -a" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	nix-donum="sudo nixos-rebuild switch --flake ~/nixos-config#donum" \
	nix-initium="sudo nixos-rebuild switch --flake ~/nixos-config#initium" \
	nix-reformata="sudo nixos-rebuild switch --flake ~/nixos-config#reformata" \
	hypr="start-hyprland" \
	ka="killall" \
	YT="youtube-viewer" \
	mpdc="mpd ~/.config/mpd/mpd.conf" \
	sdn="shutdown -h now" \
	v="$EDITOR" \
	e="emacs -nw" \
	stie="tmux new-session -s stie" \
	zigm="$HOME/.local/zig-master/zig" \
	jft="jellyfin-tui" \
	fjf="fj -H forge.matthewcloud.us" \
	fjc="fj -H codeberg.org"

alias \
	lf="lfub" \
	y="ycd" \
	gco="git_conventions" \
	cb="fj --host codeberg.org" \
	cfj="fj --host forgejo.gute-arctic.ts.net" \
	magit="nvim -c MagitOnly" \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'# lf="lfub" # y="lfcd" \

alias \
	info='fastfetch' \
	weather="curl wttr.in" \
	astroterm='astroterm --color --constellations --speed 1000 --fps 120 --city Dallas' \
	lc='linear-cli issues create' \
	lls='linear-cli issues list'

alias fzf="fzf --preview='chafa {}'"
alias ff="fd --type f | fzf | sed 's/\ /\\\ /g' "
alias ffn="fd --type f | fzf | sed 's/\ /\\\ /g' | xargs nvim"

# Run this if you ever run into errors while doing a `dotnet restore`
alias nugetclean="dotnet nuget locals --clear all"
