#!/bin/sh
# shellcheck disable=SC2155
# Profile file, runs on login. Environmental variables are set here.

# PATH Setup
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/zsh/completions:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$XDG_CONFIG_HOME/scripts:$PATH"
export PATH="$XDG_CONFIG_HOME/hypr/scripts:$PATH"
export PATH="$XDG_DATA_HOME/go/bin:$PATH"
export PATH="$XDG_CONFIG_HOME/emacs/bin:$PATH"
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"
export PATH="$HOME/.ghcup/bin:$PATH"

# macOS-specific paths
if [[ "$OSTYPE" == "darwin"* ]]; then
	export PATH="/opt/homebrew/opt/man-db/libexec/bin:$PATH"
	export PATH="/opt/homebrew/bin/cb:$PATH"
	export PATH="/opt/homebrew/bin/mpv:$PATH"
	export PATH="${PATH}:/Users/matthewkennedy/py/venv/lib/python3.13/site-packages"
fi

# Default programs
export EDITOR="nvim"
export TERMINAL="kitty"
export TERMINAL_PROG="kitty"
export BROWSER="helium-browser"
export MANPAGER="delta"

# XDG Base Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # Can break some DMs

# App-specific configurations
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"

export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_DATA_HOME/go/mod"
export ZIGPATH="$XDG_DATA_HOME/zig"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export MPD_DIR="$XDG_CONFIG_HOME/mpd"
export EMACS_DIR="$XDG_CONFIG_HOME/emacs"
export ZEIT_DB="$XDG_DATA_HOME/zeit_db"

# export NODE_PATH=$NODE_PATH:$(npm root -g)
# export GODOT="$XDG_CONFIG_HOME/godotenv/godot/bin"

# Other program settings
export DICS="/usr/share/stardict/dic/"
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --preview-window=right"
export LESS="R"
export LESS_TERMCAP_mb="$(printf '%b' '\e[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '\e[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_so="$(printf '%b' '\e[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_us="$(printf '%b' '\e[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '\e[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

# Shell settings
unsetopt PROMPT_SP 2>/dev/null

# Load shortcuts if not already loaded
[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

BEMENU_OPTS="--fn ('JetBrainsMono Nerd Font Mono [14px]')"
