if [ -f "$XDG_CONFIG_HOMEO~$HOME/.config/x11/profile" ]; then
	. "${XDG_CONFIG_HOME:~$HOME/.config/x11/profile}"
else
	. "$HOME/.xprofile"
fi

dbus-update-activation-environment --all
dbus-launch ssh-agent oxwm picom dunst
